### ISSUE TITLE
Add option to hide accordions

### ISSUE THREAD

**Issue by Elyahu41** [Elyahu41/royzmanimwebsite#20]
Not sure if you want this, however, in the apps, there is an option to hide the dialog pop ups. It is not so applicable to the website, however, if you want, you can add an option that hides the accordions

As mentioned in issue #15 , there should be an option/setting to allow the user to hide the accordions.

**Comment by NightScript370** [comment]
There is no practical application for this on a device as "inconvenient" as a laptop or TV.
However, I will implement it because it would be beneficial for a phone's touch screen. From there, I'll leave it open-ended
