### ISSUE TITLE
Add option to show shabbat mevarchim

### ISSUE THREAD

**Issue by Elyahu41** [Elyahu41/royzmanimwebsite#21]
As mentioned in issue #15 , there should be an option/setting to allow the user to see if this shabbat is shabbat mevarchim. There is a method for this in KosherZmanim that should make this trivial.

**Comment by NightScript370** [comment]
This will not be an option but rather a forced. KISS-philosophy applies
What will be an option (disabled by default), though, is the molad announcement date, because that will replace the molad calculator on the site.
