### ISSUE TITLE
Show when shabbat ends on Friday or the day before yom tov

### ISSUE THREAD

**Issue by Elyahu41** [Elyahu41/royzmanimwebsite#22]
So this feature is implemented in the backup website https://elyahu41.github.io/RabbiOvadiahYosefCalendar/ 

Change the date to any friday and you will see the red box on top of the zmanim list.

This was added as an option in the apps because some people wanted to see when shabbat ends the day beforehand. It was especially annoying because shabbat mode did not show the next day's zmanim until 12AM.

For the website, we do not need to add when shabbat ends into the list of zmanim, since we have space, we can make a separate box for it. See picture below for example. (You could also show rabbeinu tam if you have space).

As mentioned in issue #15 , there should be a box to display when shabbat/yom tov ends. Also a setting to disable this if you feel it is needed.

![Untitled](https://github.com/Elyahu41/royzmanimwebsite/assets/47622014/d907c205-6c30-44fc-8dd3-039b1eba07d2)

**Comment by NightScript370** [comment]
![image](https://github.com/Elyahu41/royzmanimwebsite/assets/18664762/bd4e3cf3-ce4a-4a12-94ae-6e241ca6916f)
My plan is to center the Parasha, then have a new line. On the right side of the new line, it will have a Havdalah candle with the time Shabbat comes out + RT in parenthesis. On the left side, it would be two flames with the time Shabbat comes in
