### ISSUE TITLE
Add options to change the theme of the website

### ISSUE THREAD

**Issue by Elyahu41** [Elyahu41/royzmanimwebsite#23]
This is really just a cosmetic thing and you can ignore this, however, it is always nice to give the user the ability to change the colors/background of the website to customize it to their liking.

As mentioned in issue #15, there should be some form of customization to the theme of the website. (No pressure for this at all as light mode and dark mode satisfy 95% of the users)

**Comment by NightScript370** [comment]
Too much customization could lead to very big confusions. The average person should not have the ability to do this.
If developers want, they could make a custom plugin using Stylize, GreeseMonkey or whatever else exists from there.

Closing...
