### ISSUE TITLE
Add option to change when candle lighting time is

### ISSUE THREAD

**Issue by Elyahu41** [Elyahu41/royzmanimwebsite#26]
As mentioned in issue #15 , there should be an option/setting to allow the user to change when candle lighting is according to his/her minhag. While the Amudei Horaah calendar put candle lighting at 18 minutes because that is the minhag. In the Ohr HaChaim calendar, it shows 20 minutes and 40 for those that are strict.

Currently there is not way to change this time.

**Comment by NightScript370** [comment]
Done in 3.0
Closing
