### ISSUE TITLE
Add option to change when shabbat ends (Ohr Hachaim only)

### ISSUE THREAD

**Issue by Elyahu41** [Elyahu41/royzmanimwebsite#27]
In Amudei Horaah mode, we display shabbat ending at 7.04 degrees after sunset. However, in Ohr HaChaim mode we show 40 minutes. 

We should show 30 minutes after sunset in Israel for the Ohr HaChaim calendar as that was Rabbi Ovadiah's psak. (Check the isInIsrael boolean)

As mentioned in issue #15 , there should also be an option/setting to allow the user to change when shabbat ends in minutes after sunset.

For example, in NY, people usually end shabbat after 50 minutes. So maybe the user wants to override the 40 minute setting.

**Comment by NightScript370** [comment]
Implemented in 3.0, even for Amudeh Hora'ah calendar
Closing...
