### ISSUE TITLE
Check users locale before changing the website

### ISSUE THREAD

**Issue by Elyahu41** [Elyahu41/royzmanimwebsite#29]
This issue is very important. If the user is in Israel or Canada or somewhere where they use a 24h clock, the website should be updated to display 24h times.

Hebrew should not be shown to the user unless they choose it for their zmanim.

You should only make the entire website Hebrew if the user's default language is in Hebrew. 

Right now, every time I open the website on a new computer, the website is entirely in hebrew. Then I need to navigate to the settings (which I do not know how it is written in hebrew) and change it there in order to use the website. The website needs to be in english first and foremost as that is our target audience. We can make another website with co.il extension for people in Israel if needed.

Either way this issue needs to be a priority.

**Comment by NightScript370** [comment]
> Right now, every time I open the website on a new computer, the website is entirely in hebrew. Then I need to navigate to the settings (which I do not know how it is written in hebrew) and change it there in order to use the website. The website needs to be in english first and foremost as that is our target audience. We can make another website with co.il extension for people in Israel if needed.

That hasn't been a thing since a week ago

> This issue is very important. If the user is in Israel or Canada or somewhere where they use a 24h clock, the website should be updated to display 24h times.

https://github.com/Elyahu41/royzmanimwebsite/commit/c84b28f04ced4b56bdddbeba9fe95560cf602e7e
