### ISSUE TITLE
Chai Tables for Netz

### ISSUE THREAD

**Issue by NightScript370** [Elyahu41/royzmanimwebsite#4]
The way the Java app has it now is that it downloads a file into its memory, converts it to data the language can understand, then use that data to get the netz timing.

For the website, we'll need to implement an API instead, since it cannot do that very first thing without being wasteful to the client side (downloading the file and its interpreter). I can easily write this in Deno and host it on my VPS.
Of course, if there is a web filter that disables access to the API link, fallback to current implementation

To implement, I will need to find the relevant Java code and see how I can replicate it from a backend perspective.
I will use a standard routing system for now, eventually replacing it with Deno.serve once it becomes stable

**Comment by NightScript370** [comment]
To solve the issue of being wasteful to the client, I have just gotten the miliseconds value themselves.
This was tested efficiently using luxon and I presume nothing changed when it came to the Temporal API rewrite other than just the basics.

The holdback now is to create a proxy because of CORS settings. Alternatively, Chaim Keller will need to be contacted about having a clear-cut CORS policy setup. That would be the most beneficial, but apparently he is hard to reach.

**Comment by Elyahu41** [comment]
Not hard to reach. He usually responds to my emails with 1 or 2 days. Have you tried emailing him? If you want, I can reach out.
